### ISSUE TITLE
Update PMP and SRS with paragraph regarding Milestone documents produced from Roy's feedback for TDD/STP

### ISSUE THREAD

**Issue by tatikozh** [umgc/fall2022#352]
Suggest both teams add a paragraph similar to the example immediately below somewhere in the beginning section/paragraph of all Milestone documents produced.  The goal of including this in all of the documents is to inform new "readers" in the future that regardless of which document they initially read - there are other documents (a suite of documents) for the app.

This is part of a set of documents created to aid in developing the USPS Informed Delivery Application and to provide artifacts with vital information for the application’s ongoing support and operation throughout its life cycle. 

The following documents are included in the entire documentation package:

- [ ] Project Plan - Version/Date
- [ ] Software Requirements Specification - Version/Date
- [ ] Technical Design Document - Version/Date
- [ ] Software Test Plan - Version/Date
- [ ] Programmers Guide - TBD until known Version/Date
- [ ] Deployment and Operations - TBD until known Version/Date
- [ ] User Guide - TBD until known Version/Date
- [ ] Test Report - TBD until known Date

**Comment by tatikozh** [comment]
Added as a new section in PMP 1.7 and a new subsection in SRS 1.4.1
